#!/bin/bash
rm /etc/udev/rules.d/aic.rules
udevadm control --reload
echo "Uninstall aic8800 wifi driver!!!!!"
rmmod aic8800_fdrv
rmmod aic_load_fw
cd /AIC8800/drivers/aic8800/aic8800_fdrv/
make clean
make uninstall
cd /AIC8800/drivers/aic8800/aic_load_fw/
make clean
make uninstall
cd /AIC8800/aicrf_test
make clean
rm -rf /lib/firmware/aic8800DC/
#exit 0
